### ISSUE TITLE
gramatical error?

### ISSUE THREAD

**Issue by def670** [etho-black/ethoprotocol_website#10]
![Screenshot from 2021-04-03 13-19-12](https://user-images.githubusercontent.com/12028110/113486152-4ab40000-947f-11eb-8bcc-69ee700abd37.png)

Im thinking it should be "DecentralizeD Content Moderation System"

**Comment by def670** [comment]
![Screenshot from 2021-04-03 13-24-23](https://user-images.githubusercontent.com/12028110/113486293-f65d5000-947f-11eb-8ede-7527e3d408e9.png)

not sure what the little graphic infront of the Decentralized bit is

**Comment by dylie** [comment]
Change of ‘the’ not necessary needed. Thanks for the input tho.

removed the fa-globe icon aswel
