### ISSUE TITLE
Scrolling text quite fast.

### ISSUE THREAD

**Issue by deslashh** [etho-black/ethoprotocol_website#11]
It swaps to next paragraph rather fast. Maybe 10s would do the trick?
![image](https://user-images.githubusercontent.com/81511499/113486461-41448b00-94b3-11eb-94b2-bd8b197af6f7.png)

**Comment by ghost** [comment]
Fixed in PR # 17

**Comment by ghost** [comment]
@deslashh , can you please test now and close this if its slow enough

**Comment by deslashh** [comment]
@newCodeRunner Make it 5 more seconds.

**Comment by ghost** [comment]
@deslashh , thanks fixed in PR # 41

**Comment by dylie** [comment]
Scrolling text speed readable, 15secs
