### ISSUE TITLE
Links not imported yet

### ISSUE THREAD

**Issue by deslashh** [etho-black/ethoprotocol_website#12]
![image](https://user-images.githubusercontent.com/81511499/113486620-1a3a8900-94b4-11eb-98a2-5c3c8f2cf727.png)

**Comment by deslashh** [comment]
![image](https://user-images.githubusercontent.com/81511499/113486627-27577800-94b4-11eb-8dee-e5531d4ded57.png)
The team members.

**Comment by deslashh** [comment]
![image](https://user-images.githubusercontent.com/81511499/113486692-61287e80-94b4-11eb-83e1-b42f15c0e489.png)
Links to medium.com home page.

**Comment by deslashh** [comment]
![image](https://user-images.githubusercontent.com/81511499/113487020-eb251700-94b5-11eb-9eea-43e65b10ce29.png)
Wallets.

**Comment by deslashh** [comment]
Explorer 1, does not react.
![image](https://user-images.githubusercontent.com/81511499/113487043-0728b880-94b6-11eb-95bf-8a217abfca2d.png)
{{FIXED}}

**Comment by deslashh** [comment]
![image](https://user-images.githubusercontent.com/81511499/113505930-0c334980-9542-11eb-8c71-c3cd4d313a95.png)
Mobile links

**Comment by Dev-JamesR** [comment]
The medium link will be updated later today. I am still writing the article about rebranding and this is where we will link to it.

**Comment by ghost** [comment]
Added mobile links in PR # 40

**Comment by dylie** [comment]
All links added and coded it the needed links to redirect into a new tab.

Only link missing is the medium article but this we know.
