### ISSUE TITLE
CSS improvements on mobile version

### ISSUE THREAD

**Issue by dylie** [etho-black/ethoprotocol_website#2]
James,

On desktop the CSS looks OK, I will look if I can fix the small details myself.

on mobile it's a acting up a bit tho. (See pics)

![mobile1](https://user-images.githubusercontent.com/38665633/113323393-33a5ce80-9316-11eb-991b-7b240e98296e.jpg)
![mobile2](https://user-images.githubusercontent.com/38665633/113323451-3f919080-9316-11eb-9efd-c68c121b3382.jpg)

**Comment by ghost** [comment]
Fixed in the PR above, but after the live version is up, we can work more on the responsiveness, it looks good on mobile and desktop but resizing the browser, at one point it breaks, so not 100% responsive still

**Comment by ghost** [comment]
@dylie , can you please verify and close this if done?

**Comment by dylie** [comment]
overall mobile css seems fine @newCodeRunner only 2 more things, is for the images on mobile, still a small sizing issue. Shouldnt be hard to fix 
![9D06F6DF-D1BC-4562-9386-9EA160AB5490](https://user-images.githubusercontent.com/38665633/113514068-dc4d6b80-956c-11eb-9488-3800eeba2480.png)
![3C2B30D0-B1A5-4289-8AEF-ED1B9ED0BECC](https://user-images.githubusercontent.com/38665633/113514073-e3747980-956c-11eb-8d7f-26776439c41e.png)

![BF67CB80-550B-477E-857F-A314D0206A61](https://user-images.githubusercontent.com/38665633/113514081-ea9b8780-956c-11eb-83f6-7d02e8d33fbb.png)

**Comment by ghost** [comment]
Fixed in PR # 38 and PR # 39. However, the images in assets folder would be need to be cropped, I see there is a lot blank space in etho black image

**Comment by dylie** [comment]
Thanks, ill crop the blankspace out tomorrow @newCodeRunner @Dev-JamesR

**Comment by dylie** [comment]
@newCodeRunner 
I got rid of the not needed blank space on the team images, now it appears that on mobile it looks good, but the images look pretty big on desk version now. The logo cropping looks fixed indeed.

**Comment by ghost** [comment]
@dylie , added max width in a PR. Please close this if it works now, this issue is getting too long to scroll down, thanks
