### ISSUE TITLE
Project Description Should Be Move Toward Center

### ISSUE THREAD

**Issue by Dev-JamesR** [etho-black/ethoprotocol_website#24]
![website1](https://user-images.githubusercontent.com/39209383/113492659-c3ba5400-948d-11eb-8a36-44fac5ffc42f.png)

**Comment by ghost** [comment]
@Dev-JamesR , if you could please merge my PRs, I will do that no problem. also on smaller screens the text overlaps the green background which (although I suck at website design) may create accessibility issues to the user in my opinion. if we could just remove it altogether (or at least decrease green background size), I will increase the padding, or if you don't mind the overlap I could still make it so

**Comment by Dev-JamesR** [comment]
If we move the description toward the center then when the screen gets smaller force css to move the description above the logo to fit on screens.

**Comment by ghost** [comment]
@Dev-JamesR , I think my recent PRs already solved this, I think it could be other way round. are you using a really large screen?

<img width="1440" alt="Screenshot 2021-04-04 at 8 05 23 PM" src="https://user-images.githubusercontent.com/57590297/113513079-3ce6a380-9581-11eb-83d1-a1218a34f9f7.png">

**Comment by Dev-JamesR** [comment]
Looks good, nice work!
