### ISSUE TITLE
CSS on the same line (prices.vue)

### ISSUE THREAD

**Issue by dylie** [etho-black/ethoprotocol_website#47]
Hey @newCodeRunner Is it possible to line these buttons up so they appear on the same height?
![Screenshot_1](https://user-images.githubusercontent.com/38665633/113598531-8c8aa500-963d-11eb-8fe1-8a6e7c50b9a4.jpg)

**Comment by ghost** [comment]
@dylie , of course it's possible :), fixed in PR #48

**Comment by dylie** [comment]
Thanks!
