### ISSUE TITLE
floating wallet on https://ethoprotocol.ether1.org/

### ISSUE THREAD

**Issue by def670** [etho-black/ethoprotocol_website#8]
view transactions button just loads an empty dropdown.  The balance on the account does load properly

**Comment by deslashh** [comment]
Also the 'back-to-top' button is aligned to bottom right an thus inside the dropdown box, which will probably sit on top of information. 
![image](https://user-images.githubusercontent.com/81511499/113485777-a8604080-94af-11eb-92e0-d5dd3bbdec2a.png)

**Comment by ghost** [comment]
tap to top button moved down in PR # 19

**Comment by dylie** [comment]
Fixed
